name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-arch-linux:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install build dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed base-devel git rust nodejs-lts pkgconf dbus libxkbcommon wayland

      - uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check
        run: cargo check --workspace

      - name: Test
        run: cargo test --workspace
